networks:
  wog-network:
    driver: bridge

services:
  web:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: flask-app
    ports:
      - "8777:8777"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - wog-network
    environment:
      - PORT=8777

  postgres:
    build:
      context: .
      dockerfile: libs/postgres/Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d wog-db"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - wog-network
    env_file:
      - .env


volumes:
  postgres_data:
