services:
  # web:
  #   build: .
  #   ports:
  #     - "8777:5000"
  #   volumes:
  #     - ./Scores.txt:/Scores.txt  # Mounting the Scores.txt file
  #   env_file:
  #     - .env

  jenkins:
    image: jenkins/jenkins:lts
    user: root  # Start as root to install packages in pipeline
    ports:
      - "8080:8080"
      - "50000:50000"
      - "8777:8777"
    working_dir: /usr/src/app
    volumes:
      - jenkins_home:/var/jenkins_home
      - .:/usr/src/app
    command: >
      /bin/bash -c "
       apt-get update &&
       apt-get install -y python3 python3-pip &&
       java -jar /usr/share/jenkins/jenkins.war
       "
    env_file:
      - .env

volumes:
  jenkins_home:
