apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: wog
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard  # Added storage class for clarity
