apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: wog
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: flask-app
          image: sahar567/wog-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8777
          envFrom:
            - configMapRef:
                name: env
            - secretRef:
                name: env-secrets
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 8777
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8777
            initialDelaySeconds: 10
            periodSeconds: 5