name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version}}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configure environment variables
      run: |
        echo "DATABASE_URL=${DATABASE_URL}" >> .env
        echo "POSTGRES_DB=${POSTGRES_DB}" >> .env
        echo "POSTGRES_USER=${POSTGRES_USER}" >> .env
        echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" >> .env
        echo "TEST_ENV=True" >> .env

    - name: Run app
      run: |
        python main.py &
        sleep 10
      env:
        TEST_ENV: True


    - name: Tests
      run: |
        python -m pytest