apiVersion: v1
kind: Secret
metadata:
  name: env-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.postgres.credentials.database_url | quote  }}
  POSTGRES_DB: {{ .Values.postgres.credentials.postgres_db | quote  }}
  POSTGRES_PASSWORD: {{ .Values.postgres.credentials.password | quote  }}
  POSTGRES_USER: {{ .Values.postgres.credentials.user | quote  }}
  SECRET_KEY: {{ .Values.postgres.credentials.secret_key | quote  }}