apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.web.containerPort }}